# Generated by Django 4.2.3 on 2023-07-31 10:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_comment_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='childcomment',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
