# Generated by Django 4.2.3 on 2023-08-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_childcomment_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='has_child',
        ),
        migrations.AddField(
            model_name='comment',
            name='child_count',
            field=models.IntegerField(default=0),
        ),
    ]
