# Generated by Django 4.2.3 on 2023-08-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_comment_has_child_comment_child_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcomment',
            name='chat',
        ),
    ]
