# Generated by Django 4.2.3 on 2023-08-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_childcomment_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcomment',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
            preserve_default=False,
        ),
    ]
