# Generated by Django 4.2.3 on 2023-08-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_childcomment_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcomment',
            name='chat',
        ),
    ]
