# Generated by Django 4.2.3 on 2023-07-31 10:08

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/default-user.png', upload_to=user.models.UploadToPath()),
        ),
    ]
